<?php
/**
 * Absolute Web Intellectual Property
 * 
 * @category     {AbsoluteWeb/cookbook}
 * @copyright    Copyright (c) 1999-2022 Absolute Web, Inc. (http://www.absoluteweb.com)
 * @author       Absolute Web
 * @license      http://www.absoluteweb.com/license-agreement/  Single domain license
 * @terms of use http://www.absoluteweb.com/terms-of-use/
 */
?>

<div class="class-instance-example">
    <h2 class="class-instance-example__header" 
        data-mage-init='{
            "AbsoluteWeb_HowToUseJsClasses/js/render": {
                "url": "https://swapi.dev/api/people/1/",
                "id": "div-id",
                "footerSelector": "footer.page-footer"
            }
        }'>Charcter info:</h2>
</div>
